### ISSUE TITLE
Options host, port, and user

### ISSUE THREAD

**Issue by RenKir** [alexevansigg/CSA-Enhanced-Operations#12]
It would be nice if host, port, and user credentials with (REST role) used by actions in the Options column, could be configurarble. It shoild be possible to specify host other than localhost, port other than 8444 and admin / ooIndboundUser password different from cloud. 
Thanks
René

**Comment by alexevansigg** [comment]
Made a commit to take the csa hostname, port and protocol from the csa.properties file
https://github.com/alexevansigg/CSA-Enhanced-Operations/commit/55fd66553d2a1763fb30cbdb0444f437b5f19bce

will have to follow up another time with the user/credentials its alittle more complex.

**Comment by alexevansigg** [comment]
Closed as per Move logger commit
