### ISSUE TITLE
Issues with CSA 4.6

### ISSUE THREAD

**Issue by xibilius** [alexevansigg/CSA-Enhanced-Operations#14]
Hello Alexander,

As you pointed out today, there is the issue with CSA 4.6 as they changed the tiles' names.
Target was changed to Type
and 
Data was changed to URL 

{      "id": "CSA-Enhanced-Operations",
    "name": "CSA-Enhanced-Operations",
    "description": "CSA-Enhanced-Operations_description",
    "enabled": true,
    "style": "custom-tile-header",
    "type": "iframe",
    "url": "/csa/custom-content/CSA-Enhanced-Operations/",
    "helptopic": "console_help",
    "roles": ["CSA_ADMIN"]
        }

Regards,

**Comment by alexevansigg** [comment]
Resolved in latest [commit](https://github.com/alexevansigg/CSA-Enhanced-Operations/commit/576f6eef31613854791fb4b80bde67c85bdad6ff)
